name = "SmartMonteCarlo"
uuid = "9228d11f-1003-4f61-918f-4dbe23b087b7"
authors = ["Sunoru <s@sunoru.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MosiBase = "a39d5f18-f8b1-4777-8f97-f1f91469dbd0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.7"
